version: '3'

services:
  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  github-release:
    image: 'github-release'
    build: './src'
